# --- Serving options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (http://username.github.io) then use these settings:
url: "https://www.jflh.ca"
baseurl: "" # the subpath of your site, e.g. /blog/

# Site settings

# Name of website
title: Keep Calm and Write Code

# Short description of your site
description: Jean-François L'Heureux's blog.

# Default site keywords
keywords: blog,development,jekyll,jflh,jflheureux,sitecore

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  About Me: "aboutme"

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/logo.png"

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Jean-François L'Heureux
  github: jflheureux
  twitter: jflh
  mastodon: https://mas.to/@jflh
  linkedin: in/jflheureux
  stackoverflow: 4891689/jflheureux

# Select which links to show in the footer
footer-links-active:
  rss: true
  facebook: false
  email: false
  twitter: true
  mastodon: true
  github: true
  linkedin: true
  stackoverflow: true

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "www.jflh.ca"  # eg. "deanattali.com/beautiful-jekyll"

# --- Misc --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
disqus: # Disabled Disqus due to ads coming

# Fill in your Google Analytics ID to track your website using GA
google_analytics: "UA-72299518-1"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "America/Montreal"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title
paginate: 5
excerpt_separator: <!-- more -->

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      author: Jean-François L'Heureux
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

# Include these files in production site
include:
  - _headers

# prose.io config
prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /_plugins
    - /css
    - /img
    - /js
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."

gems:
  - jekyll-paginate

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
